### ISSUE TITLE
Question: Why go from Avro to Protobuff?

### ISSUE THREAD

**Issue by likeabbas** [rajivr/fdb-rl-wip#1]
Hi,

I'm loosely following this repo with high hopes! This is the project I've been hoping someone would build out for years, and you're doing an amazing job. I was just wondering why you moved from Avro to Protobuf?

**Comment by rajivr** [comment]
> I was just wondering why you moved from Avro to Protobuf?

There are two dimensions that I had to consider

1. Capabilities of the serialization format
2. Implementation support in Rust

#### 1. Capabilities of the serialization format

Both Avro and Protobuf are proven serialization formats designed for row storage. "Chapter 4. Encoding and Evolution" of [Designing Data-Intensive Applications](https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/) covers both these formats in detail, so I would recommend reading that, in case you are not familiar with this resource.

There are two additional features of Protobuf that make it attractive for advanced uses cases.

1. Reflection
2. Dynamic Messages

This is possible because entities of the language is described using Protobuf itself. For example a Protobuf `message` is described using a [message descriptor](https://github.com/protocolbuffers/protobuf/blob/v22.3/src/google/protobuf/descriptor.proto#L97-L138) and this information can be made available during runtime.

Avro does not have this capability.

With Protobuf, we also get [Google Common Types](https://github.com/googleapis/googleapis/tree/2205f23a4ef0e505a5f9abf3cb54531fb4e959d9/google/type), which is missing in Avro.

#### 2. Implementation support in Rust

When I started investigating the serialization format to use, support for Protobuf reflection and dynamic messages in Rust was somewhat unclear. 

`rust-protobuf` supports reflection and dynamic messages, but the crate owner was [explicit](https://github.com/stepancheg/rust-protobuf#help) that he needed help to maintain the crate moving forward.

On the other hand, `prost` did not include support for reflection and dynamic messages in its crate.

That was when I gravitated towards using Avro. Around the same time, the maintenance of the Rust Avro crate moved upstream into the Avro project itself, which gave me a bit more confidence on the future of the Avro crate. 

If you have read the Record Layer paper, it talks about the benefit of storing schema information in the database itself rather than in code. In order to implement this, we need dynamic message support.

With Avro, I was aware of its limitation and I knew I had to figure out a way of doing something similar (which is a fair bit of additional work).

As things turned out, I then discovered [`prost-reflect`](https://github.com/andrewhickman/prost-reflect) crate.

It seems to have the exact APIs that I needed to implement schema information storage. Specifically,

- [`prost_reflect::DynamicMessage::transcode_from`](https://docs.rs/prost-reflect/0.11.3/prost_reflect/struct.DynamicMessage.html#method.transcode_from)
- [`prost_reflect::DynamicMessage::transcode_to`](https://docs.rs/prost-reflect/0.11.3/prost_reflect/struct.DynamicMessage.html#method.transcode_to)

Additionally, the `prost-reflect` code base is smaller and more tractable, in the event I had to dive in and investigate issues. This gave me the confidence to switch to Protobuf with `prost` and `prost-reflect` crates.

**Comment by likeabbas** [comment]
That makes perfect sense. I'll close the PR. I'm following this repo with great interest. I would offer to help but I don't have much experience with writing DB layers, so I will wish you good luck
